/** Stable, machine readable error codes returned in `error.code`. */
export enum ErrorCode {
  // Generic
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  NOT_FOUND = 'NOT_FOUND',
  CONFLICT = 'CONFLICT',
  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',
  RATE_LIMIT_EXCEEDED = 'RATE_LIMIT_EXCEEDED',
  PAYLOAD_TOO_LARGE = 'PAYLOAD_TOO_LARGE',
  INTERNAL_ERROR = 'INTERNAL_ERROR',

  // Auth
  EMAIL_ALREADY_REGISTERED = 'EMAIL_ALREADY_REGISTERED',
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  INVALID_REFRESH_TOKEN = 'INVALID_REFRESH_TOKEN',

  // Maps / regions
  MAP_REGION_NOT_FOUND = 'MAP_REGION_NOT_FOUND',
  MAP_REGION_FILE_NOT_AVAILABLE = 'MAP_REGION_FILE_NOT_AVAILABLE',
  MAP_DOWNLOAD_FAILED = 'MAP_DOWNLOAD_FAILED',
  INVALID_RANGE = 'INVALID_RANGE',
  CHECKSUM_MISMATCH = 'CHECKSUM_MISMATCH',
  INSUFFICIENT_STORAGE = 'INSUFFICIENT_STORAGE',

  // Routing
  ROUTE_NOT_FOUND = 'ROUTE_NOT_FOUND',
  ROUTING_PROVIDER_UNAVAILABLE = 'ROUTING_PROVIDER_UNAVAILABLE',
  ROUTING_PROFILE_NOT_SUPPORTED = 'ROUTING_PROFILE_NOT_SUPPORTED',
  INVALID_COORDINATES = 'INVALID_COORDINATES',
  INVALID_GEOMETRY = 'INVALID_GEOMETRY',

  // Geocoding
  GEOCODING_PROVIDER_UNAVAILABLE = 'GEOCODING_PROVIDER_UNAVAILABLE',

  // Domain resources
  TRIP_NOT_FOUND = 'TRIP_NOT_FOUND',
  TRIP_NOT_ACTIVE = 'TRIP_NOT_ACTIVE',
  GEOFENCE_NOT_FOUND = 'GEOFENCE_NOT_FOUND',
  PLACE_NOT_FOUND = 'PLACE_NOT_FOUND',
  SYNC_OPERATION_NOT_SUPPORTED = 'SYNC_OPERATION_NOT_SUPPORTED',
}
