"""Offline packs: what the mobile app needs to route and search a region with no connection.

A pack is one file, `<region>.rmpack`, published as the region's routing package (served by the
backend at /api/v1/maps/regions/<code>/routing/download, checked with its SHA-256):

    b"RMPACK01" | uint32 LE header length | UTF-8 JSON header, padded with spaces to 8 bytes | sections

like graph.bin (network.write_graph): each section is at `dataOffset + offset`, 8-byte aligned, little
endian. The pack has two sections:

* `graph`: the road graph of the pack area, a complete graph.bin;
* `search`: the search index of the pack area, ready to query (below).

The pack area ("coverage") is the region's bounding box plus a margin, so that routes may leave it a
little. It keeps every road with a point in that area and every search entry inside it (plus the
administrative units and places whose bounding box reaches it). Nodes, roads, names, parishes and
entries keep the order they have in the region files, so the device engine breaks ties exactly as
the backend does: on a pack that keeps the whole region, both give the same answers (tested with the
fixture of tests/fixtures/offline, generated by the backend's engines).

The search section is the in-memory index of the backend (backend/src/infrastructure/native/
native-search.ts) written out, so the device does not rebuild it:

    b"RMSRCH01" | uint32 LE header length | JSON header (counts, kinds, types, categories) | sections

    name_off/name, detail_off/detail     names and details of the entries (UTF-8, offsets uint32)
    folded_off/folded                    folded names and popular names, joined by " | "
    context_off/context                  folded details
    kind uint8, type uint16, category int32 (-1: none), lon/lat float64, bbox float32 x4 (NaN: none),
    rank uint8                           one value per entry
    name_vocab_off/name_vocab            words of the names, sorted
    name_post_off/name_post              entries of each word (int32, ascending)
    context_vocab_off/context_vocab, context_post_off/context_post   the same for the details
    grid_key float64 (sorted), grid_start uint32, grid_entry int32   places and points of interest
                                         by cell of 0.002 degrees (reverse geocoding)
"""

from __future__ import annotations

import hashlib
import json
import math
import os
import re
import struct
import sys
import unicodedata
from array import array
from pathlib import Path
from typing import Any, Iterable

PACK_MAGIC = b"RMPACK01"
SEARCH_MAGIC = b"RMSRCH01"
GRAPH_MAGIC = b"RMGRAPH2"
PACK_FORMAT = "route-maps-offline-pack"
SEARCH_FORMAT = "route-maps-search"
VERSION = 1
#: Kinds of search entries, in the order of their index (native-search.ts KINDS).
KINDS = ("admin", "place", "poi", "street")
#: Cell of the grid of places and points of interest, in degrees (native-search.ts GRID).
GRID = 0.002
#: Default margin around the region's bounding box.
MARGIN_KM = 5.0
METERS_PER_DEGREE = 111_195.08

_TYPECODES = {"int32": "i", "uint32": "I", "float32": "f", "float64": "d", "uint16": "H", "uint8": "B"}
_COMBINING = re.compile("[̀-ͯ]")
_NON_WORD = re.compile("[^0-9a-z]+")


def search_fold(text: str | None) -> str:
    """The backend's search key (native-search.ts `fold`): lower case, canonical decomposition, no
    combining accents, only ASCII letters and digits separated by one space. It differs from
    text.fold, the pipeline's key: the index must fold names exactly as the backend folds queries."""
    if not text:
        return ""
    decomposed = unicodedata.normalize("NFD", text.lower())
    return _NON_WORD.sub(" ", _COMBINING.sub("", decomposed)).strip()


# ---------------------------------------------------------------- binary layout


def _typed(values: Any, dtype: str) -> bytes:
    code = _TYPECODES[dtype]
    if isinstance(values, (bytes, bytearray)) and dtype == "uint8":
        return bytes(values)
    converted = values if isinstance(values, array) and values.typecode == code else array(code, values)
    if sys.byteorder != "little" and converted.itemsize > 1:
        converted = array(code, converted)
        converted.byteswap()
    return converted.tobytes()


def encode(magic: bytes, header: dict[str, Any], sections: Iterable[tuple[str, str, Any]]) -> bytes:
    """magic | uint32 LE header length | JSON header padded with spaces to 8 | 8-aligned sections."""
    body = bytearray()
    layout = []
    for name, dtype, values in sections:
        body += b"\0" * ((8 - len(body) % 8) % 8)
        data = _typed(values, dtype)
        layout.append({"name": name, "type": dtype, "offset": len(body),
                       "length": len(data) // struct.calcsize(_TYPECODES[dtype])})
        body += data
    encoded = json.dumps({**header, "sections": layout}, ensure_ascii=False, separators=(",", ":")).encode("utf-8")
    prefix = magic + struct.pack("<I", len(encoded)) + encoded
    prefix += b" " * ((8 - len(prefix) % 8) % 8)
    return bytes(prefix) + bytes(body)


def decode(blob: bytes, magic: bytes) -> tuple[dict[str, Any], dict[str, Any]]:
    """Header and sections (as arrays, or bytes for uint8) of a file written by `encode`."""
    if blob[:8] != magic:
        raise ValueError(f"not a {magic.decode()} file")
    (length,) = struct.unpack_from("<I", blob, 8)
    header = json.loads(blob[12:12 + length].decode("utf-8"))
    data = (12 + length + 7) // 8 * 8
    sections: dict[str, Any] = {}
    for section in header["sections"]:
        code = _TYPECODES[section["type"]]
        size = struct.calcsize(code)
        start = data + section["offset"]
        raw = blob[start:start + section["length"] * size]
        if code == "B":
            sections[section["name"]] = bytes(raw)
            continue
        values = array(code)
        values.frombytes(raw)
        if sys.byteorder != "little" and size > 1:
            values.byteswap()
        sections[section["name"]] = values
    return header, sections


def _strings(values: list[str]) -> tuple[array, bytes]:
    blob = bytearray()
    offsets = array("I", [0])
    for value in values:
        blob += value.encode("utf-8")
        offsets.append(len(blob))
    return offsets, bytes(blob)


# ---------------------------------------------------------------- area


def coverage_of(bbox: list[float], margin_km: float) -> list[float]:
    """The bounding box plus `margin_km` on every side."""
    min_lon, min_lat, max_lon, max_lat = bbox
    if not (min_lon < max_lon and min_lat < max_lat):
        raise ValueError(f"invalid bounding box {bbox}")
    dlat = margin_km * 1000 / METERS_PER_DEGREE
    widest = max(abs(min_lat), abs(max_lat))
    dlon = dlat / max(math.cos(math.radians(min(widest + dlat, 89.0))), 0.01)
    return [round(max(-180.0, min_lon - dlon), 6), round(max(-90.0, min_lat - dlat), 6),
            round(min(180.0, max_lon + dlon), 6), round(min(90.0, max_lat + dlat), 6)]


def _intersects(box: tuple[float, float, float, float], area: list[float]) -> bool:
    return box[0] <= area[2] and box[2] >= area[0] and box[1] <= area[3] and box[3] >= area[1]


# ---------------------------------------------------------------- graph


def clip_graph(blob: bytes, area: list[float]) -> tuple[bytes, dict[str, int]]:
    """The graph.bin of the roads with a point in `area`: same layout, renumbered in their order."""
    header, sections = decode(blob, GRAPH_MAGIC)
    if header.get("format") != "route-maps-graph" or header.get("version") != 2:
        raise ValueError(f"unsupported graph {header.get('format')} v{header.get('version')}")
    node_lon, node_lat = sections["node_lon"], sections["node_lat"]
    edge_u, edge_v = sections["edge_u"], sections["edge_v"]
    shape_off, shape_lon, shape_lat = sections["shape_off"], sections["shape_lon"], sections["shape_lat"]
    edge_name, edge_ref, edge_parish = sections["edge_name"], sections["edge_ref"], sections["edge_parish"]

    kept = []
    for edge in range(header["counts"]["edges"]):
        u, v = edge_u[edge], edge_v[edge]
        lons = [node_lon[u], node_lon[v], *shape_lon[shape_off[edge]:shape_off[edge + 1]]]
        lats = [node_lat[u], node_lat[v], *shape_lat[shape_off[edge]:shape_off[edge + 1]]]
        if _intersects((min(lons) / 1e7, min(lats) / 1e7, max(lons) / 1e7, max(lats) / 1e7), area):
            kept.append(edge)

    nodes = sorted({edge_u[edge] for edge in kept} | {edge_v[edge] for edge in kept})
    node_id = {old: new for new, old in enumerate(nodes)}
    used_names = sorted({edge_name[edge] for edge in kept if edge_name[edge] >= 0}
                        | {edge_ref[edge] for edge in kept if edge_ref[edge] >= 0})
    name_id = {old: new for new, old in enumerate(used_names)}
    used_parishes = sorted({edge_parish[edge] for edge in kept if edge_parish[edge] >= 0})
    parish_id = {old: new for new, old in enumerate(used_parishes)}

    names_off, names = sections["names_off"], sections["names"]
    name_values = [names[names_off[old]:names_off[old + 1]].decode("utf-8") for old in used_names]
    new_shape_off = array("I", [0])
    new_shape_lon = array("i")
    new_shape_lat = array("i")
    for edge in kept:
        new_shape_lon.extend(shape_lon[shape_off[edge]:shape_off[edge + 1]])
        new_shape_lat.extend(shape_lat[shape_off[edge]:shape_off[edge + 1]])
        new_shape_off.append(len(new_shape_lon))
    new_names_off, new_names = _strings(name_values)

    def remap(values: array, table: dict[int, int]) -> array:
        return array("i", (table[values[edge]] if values[edge] >= 0 else -1 for edge in kept))

    parishes = header.get("parishes") or []
    out = {key: value for key, value in header.items() if key not in ("counts", "parishes", "sections")}
    out["counts"] = {"nodes": len(nodes), "edges": len(kept), "names": len(name_values)}
    out["parishes"] = [parishes[old] for old in used_parishes]
    out["coverage"] = area
    encoded = encode(GRAPH_MAGIC, out, [
        ("node_lon", "int32", array("i", (node_lon[node] for node in nodes))),
        ("node_lat", "int32", array("i", (node_lat[node] for node in nodes))),
        ("edge_u", "int32", array("i", (node_id[edge_u[edge]] for edge in kept))),
        ("edge_v", "int32", array("i", (node_id[edge_v[edge]] for edge in kept))),
        ("edge_len", "float32", array("f", (sections["edge_len"][edge] for edge in kept))),
        ("edge_cls", "uint8", bytes(sections["edge_cls"][edge] for edge in kept)),
        ("edge_flags", "uint8", bytes(sections["edge_flags"][edge] for edge in kept)),
        ("edge_name", "int32", remap(edge_name, name_id)),
        ("edge_ref", "int32", remap(edge_ref, name_id)),
        ("edge_parish", "int32", remap(edge_parish, parish_id)),
        ("shape_off", "uint32", new_shape_off),
        ("shape_lon", "int32", new_shape_lon),
        ("shape_lat", "int32", new_shape_lat),
        ("names_off", "uint32", new_names_off),
        ("names", "uint8", new_names),
    ])
    return encoded, {"nodes": len(nodes), "edges": len(kept)}


# ---------------------------------------------------------------- search


def read_entries(path: Path) -> list[dict[str, Any]]:
    entries = []
    with path.open(encoding="utf-8") as handle:
        for line in handle:
            if line.strip():
                entries.append(json.loads(line))
    return entries


def in_area(entry: dict[str, Any], area: list[float]) -> bool:
    """Entries inside the area, and the units and places that reach it (its province, its canton)."""
    x, y = entry.get("x"), entry.get("y")
    if isinstance(x, (int, float)) and isinstance(y, (int, float)) and area[0] <= x <= area[2] \
            and area[1] <= y <= area[3]:
        return True
    box = entry.get("b")
    return entry.get("k") in ("admin", "place") and isinstance(box, list) and len(box) == 4 \
        and _intersects(tuple(box), area)


def grid_key(lon: float, lat: float) -> int:
    """native-search.ts gridKey."""
    return (math.floor(lat / GRID) + 100_000) * 400_000 + (math.floor(lon / GRID) + 200_000)


def search_index(entries: list[dict[str, Any]]) -> bytes:
    """The search section: NativeSearchIndex of the backend, built from these entries."""
    names, details, folded, contexts = [], [], [], []
    kinds, ranks = bytearray(), bytearray()
    types, categories = array("H"), array("i")
    lons, lats, boxes = array("d"), array("d"), array("f")
    type_ids: dict[str, int] = {}
    category_ids: dict[str, int] = {}
    name_words: dict[str, array] = {}
    context_words: dict[str, array] = {}
    grid: dict[int, array] = {}
    nan = float("nan")
    for index, entry in enumerate(entries):
        all_names = [value for value in (search_fold(text) for text in [entry["n"], *(entry.get("a") or [])])
                     if value]
        context = search_fold(entry.get("d"))
        names.append(entry["n"])
        details.append(entry.get("d") or "")
        folded.append(" | ".join(all_names))
        contexts.append(context)
        kind = entry.get("k")
        kinds.append(KINDS.index(kind) if kind in KINDS else 0)
        types.append(type_ids.setdefault(entry.get("t") or "", len(type_ids)))
        category = entry.get("c")
        categories.append(category_ids.setdefault(category, len(category_ids)) if category is not None else -1)
        lons.append(float(entry["x"]))
        lats.append(float(entry["y"]))
        box = entry.get("b")
        boxes.extend([float(value) for value in box] if box else [nan] * 4)
        ranks.append(int(max(0, min(255, entry["r"]))))
        for token in dict.fromkeys(" ".join(all_names).split(" ")):
            if token and token != "|":
                name_words.setdefault(token, array("i")).append(index)
        for token in dict.fromkeys(context.split(" ")):
            if token:
                context_words.setdefault(token, array("i")).append(index)
        if kind in ("poi", "place"):
            grid.setdefault(grid_key(entry["x"], entry["y"]), array("i")).append(index)

    def postings(words: dict[str, array]) -> list[tuple[str, str, Any]]:
        vocabulary = sorted(words)
        offsets = array("I", [0])
        lists = array("i")
        for word in vocabulary:
            lists.extend(words[word])
            offsets.append(len(lists))
        vocab_off, vocab = _strings(vocabulary)
        return [("vocab_off", "uint32", vocab_off), ("vocab", "uint8", vocab),
                ("post_off", "uint32", offsets), ("post", "int32", lists)]

    keys = sorted(grid)
    starts = array("I", [0])
    cells = array("i")
    for key in keys:
        cells.extend(grid[key])
        starts.append(len(cells))
    sections: list[tuple[str, str, Any]] = []
    for name, values in (("name", names), ("detail", details), ("folded", folded), ("context", contexts)):
        offsets, blob = _strings(values)
        sections += [(f"{name}_off", "uint32", offsets), (name, "uint8", blob)]
    sections += [("kind", "uint8", bytes(kinds)), ("type", "uint16", types), ("category", "int32", categories),
                 ("lon", "float64", lons), ("lat", "float64", lats), ("bbox", "float32", boxes),
                 ("rank", "uint8", bytes(ranks))]
    sections += [(f"name_{name}", dtype, values) for name, dtype, values in postings(name_words)]
    sections += [(f"context_{name}", dtype, values) for name, dtype, values in postings(context_words)]
    sections += [("grid_key", "float64", array("d", (float(key) for key in keys))),
                 ("grid_start", "uint32", starts), ("grid_entry", "int32", cells)]
    header = {
        "format": SEARCH_FORMAT, "version": VERSION,
        "counts": {"entries": len(entries), "nameWords": len(name_words), "contextWords": len(context_words),
                   "cells": len(keys)},
        "kinds": list(KINDS), "types": list(type_ids), "categories": list(category_ids), "grid": GRID,
    }
    return encode(SEARCH_MAGIC, header, sections)


# ---------------------------------------------------------------- pack


def build_pack(graph_path: Path, search_path: Path, *, bbox: list[float], margin_km: float = MARGIN_KM,
               region: str, name: str) -> tuple[bytes, dict[str, Any]]:
    """The pack of a region and its summary. The same inputs always give the same bytes (no build
    time), so a rebuild of unchanged data does not make the devices download it again."""
    area = coverage_of(bbox, margin_km)
    graph_blob = graph_path.read_bytes()
    search_blob = search_path.read_bytes()
    graph, counts = clip_graph(graph_blob, area)
    entries = [entry for entry in read_entries(search_path) if in_area(entry, area)]
    search = search_index(entries)
    (length,) = struct.unpack_from("<I", graph_blob, 8)
    source = json.loads(graph_blob[12:12 + length].decode("utf-8"))
    header: dict[str, Any] = {
        "format": PACK_FORMAT, "version": VERSION, "region": region, "name": name,
        "bbox": [float(value) for value in bbox], "coverage": area,
    }
    if source.get("builtAt"):
        header["builtAt"] = source["builtAt"]
    header["sources"] = {"graph": hashlib.sha256(graph_blob).hexdigest(),
                         "search": hashlib.sha256(search_blob).hexdigest()}
    header["counts"] = {**counts, "entries": len(entries)}
    pack = encode(PACK_MAGIC, header, [("graph", "uint8", graph), ("search", "uint8", search)])
    summary = {key: header[key] for key in ("region", "name", "coverage", "counts")}
    summary["bytes"] = len(pack)
    summary["sha256"] = hashlib.sha256(pack).hexdigest()
    return pack, summary


def write_pack(graph_path: Path, search_path: Path, output: Path, **options: Any) -> dict[str, Any]:
    """Builds the pack into `output`, through a temporary file renamed when complete."""
    pack, summary = build_pack(graph_path, search_path, **options)
    output.parent.mkdir(parents=True, exist_ok=True)
    temporary = output.with_name(f".{output.name}.part")
    with temporary.open("wb") as handle:
        handle.write(pack)
        handle.flush()
        os.fsync(handle.fileno())
    os.chmod(temporary, 0o644)
    temporary.replace(output)
    return {**summary, "file": str(output)}
