import { HttpStatus, Inject, Injectable } from '@nestjs/common';
import { ACCOUNT_ACCESS, type AccountAccessReader } from '../../../common/auth/auth-ports';
import { Paginated } from '../../../common/dto/pagination.dto';
import { AppException } from '../../../common/errors/app.exception';
import { ErrorCode } from '../../../common/errors/error-codes';
import { Prisma } from '../../../generated/prisma/client';
import { DevicePlatform, TripStatus, UserRole } from '../../../generated/prisma/enums';
import { PrismaService } from '../../../infrastructure/prisma/prisma.service';
import { AuditActor, AuditService } from '../../audit/application/audit.service';
import { PASSWORD_HASHER, type PasswordHasher } from '../../auth/domain/password-hasher';
import { UsersService } from '../../users/application/users.service';
import { generateTemporaryPassword } from '../domain/temporary-password';
import {
  CreateUserDto,
  ListUsersQueryDto,
  LookupAccountsQueryDto,
  ResetPasswordDto,
  UpdateUserDto,
} from './dto/admin.dto';

export interface AdminUserView {
  id: string;
  email: string;
  name: string;
  role: UserRole;
  active: boolean;
  /** Account of an integration: it never signs in with a password. */
  serviceAccount: boolean;
  lastLoginAt: Date | null;
  createdAt: Date;
  updatedAt: Date;
  counts: { devices: number; trips: number; integrations: number };
}

export interface AdminDeviceSummary {
  id: string;
  installationId: string;
  platform: DevicePlatform;
  model: string | null;
  appVersion: string | null;
  lastSeenAt: Date;
  createdAt: Date;
}

export interface AdminUserDetail extends AdminUserView {
  /** Sessions opened before this instant were closed by an administrator or a new password. */
  sessionsRevokedAt: Date | null;
  counts: AdminUserView['counts'] & {
    activeTrips: number;
    geofences: number;
    places: number;
    routes: number;
    /** Refresh tokens still usable (signed-in apps or panel sessions). */
    activeSessions: number;
  };
  devices: AdminDeviceSummary[];
  integrations: { id: string; name: string; active: boolean }[];
}

/** What the account pickers of the panel show. */
export interface AccountOption {
  id: string;
  email: string;
  name: string;
  role: UserRole;
  active: boolean;
  serviceAccount: boolean;
}

/** A password generated by the platform, shown to the administrator once. */
export interface PasswordOutcome {
  temporaryPassword: string | null;
}

const USER_SELECT = {
  id: true,
  email: true,
  name: true,
  role: true,
  active: true,
  serviceAccount: true,
  lastLoginAt: true,
  createdAt: true,
  updatedAt: true,
  _count: { select: { devices: true, trips: true, integrations: true } },
} satisfies Prisma.UserSelect;

type UserRow = Prisma.UserGetPayload<{ select: typeof USER_SELECT }>;

const toView = ({ _count, ...user }: UserRow): AdminUserView => ({ ...user, counts: _count });

/** Most devices the account detail lists (most recently seen first). */
const DETAIL_DEVICES = 50;

/**
 * Accounts of the platform (administration): people who sign in to the app or the panel, and the
 * service accounts integrations act as. Every change is written to the audit log, and the
 * platform always keeps at least one active administrator.
 */
@Injectable()
export class AdminUsersService {
  constructor(
    private readonly prisma: PrismaService,
    private readonly users: UsersService,
    private readonly audit: AuditService,
    @Inject(PASSWORD_HASHER) private readonly hasher: PasswordHasher,
    @Inject(ACCOUNT_ACCESS) private readonly accounts: AccountAccessReader,
  ) {}

  async list(query: ListUsersQueryDto): Promise<Paginated<AdminUserView>> {
    const where: Prisma.UserWhereInput = {
      ...(query.kind === 'people' ? { serviceAccount: false } : {}),
      ...(query.kind === 'service' ? { serviceAccount: true } : {}),
      ...(query.role ? { role: query.role } : {}),
      ...(query.active !== undefined ? { active: query.active } : {}),
      ...(query.q
        ? {
            OR: [
              { email: { contains: query.q, mode: 'insensitive' } },
              { name: { contains: query.q, mode: 'insensitive' } },
            ],
          }
        : {}),
    };
    const [rows, total] = await Promise.all([
      this.prisma.user.findMany({
        where,
        select: USER_SELECT,
        orderBy: [{ createdAt: 'desc' }, { id: 'asc' }],
        take: query.limit,
        skip: query.offset,
      }),
      this.prisma.user.count({ where }),
    ]);
    return { items: rows.map(toView), total, limit: query.limit, offset: query.offset };
  }

  /** Accounts whose email starts with the text first, then those that contain it. */
  async lookup(query: LookupAccountsQueryDto): Promise<AccountOption[]> {
    const text = query.q.toLowerCase();
    const rows = await this.prisma.user.findMany({
      where: {
        OR: [
          { email: { contains: text, mode: 'insensitive' } },
          { name: { contains: text, mode: 'insensitive' } },
        ],
      },
      select: {
        id: true,
        email: true,
        name: true,
        role: true,
        active: true,
        serviceAccount: true,
      },
      orderBy: [{ email: 'asc' }],
      // Enough candidates to put the accounts that start with the text first.
      take: query.limit * 5,
    });
    const starts = (row: AccountOption) => (row.email.startsWith(text) ? 0 : 1);
    return rows.sort((a, b) => starts(a) - starts(b)).slice(0, query.limit);
  }

  async get(id: string): Promise<AdminUserDetail> {
    const now = new Date();
    const user = await this.prisma.user.findUnique({
      where: { id },
      select: {
        ...USER_SELECT,
        sessionsRevokedAt: true,
        _count: {
          select: {
            devices: true,
            trips: true,
            integrations: true,
            geofences: true,
            places: true,
            routes: true,
          },
        },
        devices: {
          orderBy: { lastSeenAt: 'desc' },
          take: DETAIL_DEVICES,
          select: {
            id: true,
            installationId: true,
            platform: true,
            model: true,
            appVersion: true,
            lastSeenAt: true,
            createdAt: true,
          },
        },
        integrations: {
          orderBy: { createdAt: 'asc' },
          select: { id: true, name: true, active: true },
        },
      },
    });
    if (!user) throw AppException.notFound(ErrorCode.USER_NOT_FOUND, 'User not found');
    const [activeTrips, activeSessions] = await Promise.all([
      this.prisma.trip.count({ where: { userId: id, status: TripStatus.ACTIVE } }),
      this.prisma.refreshToken.count({
        where: { userId: id, revokedAt: null, expiresAt: { gt: now } },
      }),
    ]);
    const { _count, devices, integrations, ...rest } = user;
    return {
      ...rest,
      counts: { ..._count, activeTrips, activeSessions },
      devices,
      integrations,
    };
  }

  /** Creates an account; without a password one is generated and returned only here. */
  async create(
    actor: AuditActor,
    dto: CreateUserDto,
  ): Promise<{ user: AdminUserDetail } & PasswordOutcome> {
    if (await this.users.findByEmail(dto.email)) {
      throw new AppException(
        ErrorCode.EMAIL_ALREADY_REGISTERED,
        'Email is already registered',
        HttpStatus.CONFLICT,
      );
    }
    const temporaryPassword = dto.password ? null : generateTemporaryPassword();
    const passwordHash = await this.hasher.hash(dto.password ?? temporaryPassword!);
    // With its audit entry: a failure must not leave the account with a password nobody saw.
    const user = await this.prisma.$transaction(async (tx) => {
      const created = await this.users.create(
        { email: dto.email, name: dto.name, role: dto.role, passwordHash },
        tx,
      );
      await this.audit.record(
        actor,
        {
          action: 'user.create',
          targetType: 'user',
          targetId: created.id,
          summary: created.email,
          details: { role: created.role, generatedPassword: temporaryPassword !== null },
        },
        tx,
      );
      return created;
    });
    return { user: await this.get(user.id), temporaryPassword };
  }

  /**
   * Changes the name, role or state of an account. Disabling it closes its sessions at once;
   * nobody can change their own role or state, and the last active administrator stays one.
   */
  async update(actor: AuditActor, id: string, dto: UpdateUserDto): Promise<AdminUserDetail> {
    const user = await this.users.getById(id);
    const changes: Record<string, { from: unknown; to: unknown }> = {};
    if (dto.name !== undefined && dto.name !== user.name) {
      changes.name = { from: user.name, to: dto.name };
    }
    if (dto.role !== undefined && dto.role !== user.role) {
      changes.role = { from: user.role, to: dto.role };
    }
    if (dto.active !== undefined && dto.active !== user.active) {
      changes.active = { from: user.active, to: dto.active };
    }
    if (Object.keys(changes).length === 0) return this.get(id);

    if ((changes.role || changes.active) && id === actor.id) {
      throw this.selfChange('You cannot change your own role or disable your own account');
    }
    if (changes.role && user.serviceAccount) {
      throw new AppException(
        ErrorCode.VALIDATION_ERROR,
        'Accounts of integrations always have the USER role',
      );
    }
    const disabling = dto.active === false && changes.active !== undefined;
    await this.prisma.$transaction(async (tx) => {
      if ((changes.role && dto.role !== UserRole.ADMIN) || disabling) {
        await this.keepAnAdministrator(tx, id);
      }
      await tx.user.update({
        where: { id },
        data: {
          name: changes.name ? dto.name : undefined,
          role: changes.role ? dto.role : undefined,
          active: changes.active ? dto.active : undefined,
          // Tokens issued before being disabled must not work again if it is enabled later.
          ...(disabling ? { sessionsRevokedAt: new Date() } : {}),
        },
      });
      if (disabling) {
        await tx.refreshToken.updateMany({
          where: { userId: id, revokedAt: null },
          data: { revokedAt: new Date() },
        });
      }
    });
    this.accounts.invalidate(id);
    await this.audit.record(actor, {
      action: changes.active
        ? dto.active
          ? 'user.enable'
          : 'user.disable'
        : changes.role
          ? 'user.role'
          : 'user.update',
      targetType: 'user',
      targetId: id,
      summary: user.email,
      details: changes,
    });
    return this.get(id);
  }

  /** Sets a new password (generated when absent) and closes every session of the account. */
  async resetPassword(
    actor: AuditActor,
    id: string,
    dto: ResetPasswordDto,
  ): Promise<PasswordOutcome> {
    const user = await this.users.getById(id);
    if (id === actor.id) {
      throw this.selfChange('Change your own password from your account');
    }
    if (user.serviceAccount) {
      throw new AppException(
        ErrorCode.VALIDATION_ERROR,
        'Accounts of integrations do not sign in with a password',
      );
    }
    const temporaryPassword = dto.password ? null : generateTemporaryPassword();
    const passwordHash = await this.hasher.hash(dto.password ?? temporaryPassword!);
    await this.prisma.$transaction(async (tx) => {
      await this.users.replacePassword(id, passwordHash, tx);
      await this.audit.record(
        actor,
        {
          action: 'user.password_reset',
          targetType: 'user',
          targetId: id,
          summary: user.email,
          details: { generatedPassword: temporaryPassword !== null },
        },
        tx,
      );
    });
    this.accounts.invalidate(id);
    return { temporaryPassword };
  }

  /** Signs the account out everywhere: apps and panel sessions must sign in again. */
  async revokeSessions(actor: AuditActor, id: string): Promise<{ revoked: true }> {
    const user = await this.users.getById(id);
    if (id === actor.id) throw this.selfChange('Sign out to close your own session');
    await this.users.revokeSessions(id);
    this.accounts.invalidate(id);
    await this.audit.record(actor, {
      action: 'user.sessions_revoke',
      targetType: 'user',
      targetId: id,
      summary: user.email,
    });
    return { revoked: true };
  }

  /**
   * Deletes the account with everything it holds (devices, trips, places, geofences, routes).
   * Accounts used by integrations are kept until those integrations are deleted.
   */
  async delete(actor: AuditActor, id: string): Promise<{ deleted: true }> {
    const user = await this.users.getById(id);
    if (id === actor.id) throw this.selfChange('You cannot delete your own account');
    const integrations = await this.prisma.integration.count({ where: { userId: id } });
    if (integrations > 0) {
      throw new AppException(
        ErrorCode.CONFLICT,
        `This account is used by ${integrations} integration(s): delete them first`,
        HttpStatus.CONFLICT,
      );
    }
    await this.prisma.$transaction(async (tx) => {
      await this.keepAnAdministrator(tx, id);
      await tx.user.delete({ where: { id } });
    });
    this.accounts.invalidate(id);
    await this.audit.record(actor, {
      action: 'user.delete',
      targetType: 'user',
      targetId: id,
      summary: user.email,
      details: { role: user.role, serviceAccount: user.serviceAccount },
    });
    return { deleted: true };
  }

  /**
   * Refuses a change that would leave no active administrator. The administrators are locked
   * until the transaction ends, so two administrators demoting each other cannot both succeed.
   */
  private async keepAnAdministrator(tx: Prisma.TransactionClient, id: string): Promise<void> {
    const admins = await tx.$queryRaw<{ id: string }[]>`
      SELECT id FROM users WHERE role = 'ADMIN' AND active ORDER BY id FOR UPDATE`;
    if (admins.length === 1 && admins[0].id === id) {
      throw new AppException(
        ErrorCode.LAST_ADMINISTRATOR,
        'The platform needs at least one active administrator',
        HttpStatus.CONFLICT,
      );
    }
  }

  private selfChange(message: string): AppException {
    return new AppException(ErrorCode.SELF_CHANGE_NOT_ALLOWED, message, HttpStatus.CONFLICT);
  }
}
