import 'dart:convert';
import 'dart:io';

import 'package:flutter_test/flutter_test.dart';
import 'package:maps_platform/infrastructure/offline/fold.dart';
import 'package:maps_platform/infrastructure/offline/offline_pack.dart';
import 'package:maps_platform/infrastructure/offline/road_router.dart';

import 'offline_fixture.dart';

/// The phone must answer exactly as the platform: expected.json holds what the backend's engines
/// answer on the fixture city, and fixture.rmpack is the offline pack the data pipeline builds
/// from the same data (both regenerated by `npm run fixtures:offline` in backend/).
void main() {
  final expected = readExpected();
  final pack = OfflinePack.open(fixturePack);

  test('folds text exactly as the backend', () {
    for (final pair in expected['folds']! as List<Object?>) {
      final [text as String, folded as String] = pair! as List<Object?>;
      expect(fold(text), folded, reason: jsonEncode(text));
    }
  });

  test('the pack covers the fixture city', () {
    final city = (expected['packs']! as List<Object?>).first! as Map<String, Object?>;
    final [west as num, south as num, east as num, north as num] = city['bbox']! as List<Object?>;
    expect(pack.region, city['region']);
    expect(pack.covers(west.toDouble(), south.toDouble()), isTrue);
    expect(pack.covers(east.toDouble(), north.toDouble()), isTrue);
    expect(pack.graph.edgeCount, greaterThan(100));
    expect(pack.places.size, greaterThan(50));
  });

  group('routes like the platform:', () {
    for (final item in expected['routes']! as List<Object?>) {
      final query = item! as Map<String, Object?>;
      test(query['name']! as String, () {
        final stops = [
          for (final stop in query['stops']! as List<Object?>)
            if (stop case [final num longitude, final num latitude])
              (longitude: longitude.toDouble(), latitude: latitude.toDouble()),
        ];
        final alternatives = stops.length > 2 ? 0 : (query['alternatives']! as num).toInt();
        Map<String, Object?> route() {
          final result = pack.router.route(
            query['profile']! as String,
            stops,
            alternatives,
            language: query['language'] as String?,
          );
          return {'primary': result.primary, 'alternatives': result.alternatives};
        }

        if (query['error'] case final String message) {
          expect(
            route,
            throwsA(isA<NoRouteError>().having((error) => error.message, 'message', message)),
          );
        } else {
          expect(route(), query['result']);
        }
      });
    }
  });

  group('searches like the platform:', () {
    for (final item in expected['searches']! as List<Object?>) {
      final query = item! as Map<String, Object?>;
      final near = query['near'] as List<Object?>?;
      test('"${query['text']}"${near == null ? '' : ' near $near'}', () {
        final results = pack.geocoder.search(
          query['text']! as String,
          limit: (query['limit']! as num).toInt(),
          nearLongitude: (near?[0] as num?)?.toDouble(),
          nearLatitude: (near?[1] as num?)?.toDouble(),
        );
        expect(results, query['results']);
      });
    }
  });

  group('finds addresses like the platform:', () {
    for (final item in expected['reverses']! as List<Object?>) {
      final query = item! as Map<String, Object?>;
      final [longitude as num, latitude as num] = query['point']! as List<Object?>;
      test('at ${query['point']}', () {
        expect(pack.geocoder.reverse(latitude.toDouble(), longitude.toDouble()), query['result']);
      });
    }
  });
}
