import 'dart:convert';
import 'dart:io';

/// The offline fixture shared with the backend and the data pipeline
/// (infrastructure/data-tools/tests/fixtures/offline, regenerated by `npm run fixtures:offline`
/// in backend/).
const fixtureDirectory = '../infrastructure/data-tools/tests/fixtures/offline';

/// The whole fixture city, which answers exactly like the backend.
const fixturePack = '$fixtureDirectory/fixture.rmpack';

/// Durán alone, inside the city.
const duranPack = '$fixtureDirectory/fixture-duran.rmpack';

Map<String, Object?> readExpected() =>
    jsonDecode(File('$fixtureDirectory/expected.json').readAsStringSync()) as Map<String, Object?>;
