import { join } from 'node:path';
import { NativeGraph } from '../../infrastructure/native/native-graph';
import { NativeGraphStore } from '../../infrastructure/native/native-graph.store';
import { NativeSearchIndex, fold } from '../../infrastructure/native/native-search';
import { NativeSearchStore } from '../../infrastructure/native/native-search.store';
import { encodeGraph } from '../../infrastructure/native/testing/graph-fixture';
import { NativeGeocodingProvider } from '../../modules/geocoding/infrastructure/native-geocoding.provider';
import {
  NativeRouter,
  NoRouteError,
} from '../../modules/routing/infrastructure/native/native-router';
import { FIXTURE_GRAPH, FIXTURE_SEARCH } from './fixture-city';
import { FOLD_CASES, REVERSE_QUERIES, ROUTE_QUERIES, SEARCH_QUERIES } from './fixture-queries';

/**
 * Files of the offline parity fixture, shared by the three implementations:
 *
 *   graph.bin, search.ndjson  the fixture city, as the data pipeline writes a region (this file)
 *   expected.json             what the server's engines answer on it (this file)
 *   fixture.rmpack            the offline pack the data tools build from them (native-data pack)
 *
 * The mobile app's tests load fixture.rmpack and must answer exactly expected.json.
 * Regenerate everything with `npm run fixtures:offline` after changing the engines or the city.
 */
export const FIXTURE_DIR = join(
  __dirname,
  '..',
  '..',
  '..',
  '..',
  'infrastructure',
  'data-tools',
  'tests',
  'fixtures',
  'offline',
);

/** The search fold of the mobile app, generated from the backend's (see foldTable). */
export const FOLD_TABLE_FILE = join(
  __dirname,
  '..',
  '..',
  '..',
  '..',
  'mobile',
  'lib',
  'infrastructure',
  'offline',
  'fold_table.dart',
);

export interface FixturePack {
  file: string;
  region: string;
  name: string;
  bbox: [number, number, number, number];
  marginKm: number;
}

/**
 * Offline packs built from the fixture: the whole city, so that it answers exactly like the full
 * graph (its margin also covers the far points of the routes that fail), and Durán alone, inside
 * it, for the app's choice between packs.
 */
export const FIXTURE_PACKS: FixturePack[] = [
  {
    file: 'fixture.rmpack',
    region: 'fixture',
    name: 'Fixture city',
    bbox: [-79.95, -2.25, -79.75, -2.15],
    marginKm: 40,
  },
  {
    file: 'fixture-duran.rmpack',
    region: 'fixture-duran',
    name: 'Durán',
    bbox: [-79.84, -2.21, -79.81, -2.19],
    marginKm: 0,
  },
];

export interface FixtureFiles {
  'graph.bin': Buffer;
  'search.ndjson': string;
  'expected.json': string;
}

export async function buildFixtureFiles(): Promise<FixtureFiles> {
  const graphBin = encodeGraph(FIXTURE_GRAPH);
  const graph = NativeGraph.parse(graphBin);
  const index = NativeSearchIndex.fromEntries(FIXTURE_SEARCH);
  const expected = await answers(graph, index);
  return {
    'graph.bin': graphBin,
    'search.ndjson': FIXTURE_SEARCH.map((entry) => JSON.stringify(entry)).join('\n') + '\n',
    'expected.json': serialize(expected),
  };
}

/**
 * Dart source of the characters the backend's `fold` turns into an ASCII letter or digit: the app
 * folds queries with it, so it must stay generated from the backend's own Unicode data. Each
 * character is folded between two letters: it becomes a letter, a separator or nothing (only the
 * combining marks U+0300 to U+036F, which the Dart fold drops by range).
 */
export function foldTable(): string {
  const pairs: string[] = [];
  for (let code = 0x80; code <= 0xffff; code += 1) {
    if (code >= 0xd800 && code <= 0xdfff) continue;
    const folded = fold(`a${String.fromCharCode(code)}b`);
    if (folded === 'a b') continue;
    if (folded === 'ab' && code >= 0x300 && code <= 0x36f) continue;
    const letter = /^a([0-9a-z])b$/.exec(folded);
    if (!letter)
      throw new Error(`U+${code.toString(16)} folds to "${folded}": extend the Dart fold`);
    pairs.push(`\\u${code.toString(16).padStart(4, '0')}${letter[1]}`);
  }
  const lines: string[] = [];
  for (let start = 0; start < pairs.length; start += 12) {
    lines.push(`    '${pairs.slice(start, start + 12).join('')}'`);
  }
  return [
    "// Generated by `npm run fixtures:offline` in backend/ from the backend's search fold",
    '// (native-search.ts `fold`): do not edit.',
    '',
    '/// Every character of the Basic Multilingual Plane that the backend folds to an ASCII letter or',
    '/// digit (lower case, canonical decomposition, no combining accents), followed by that letter.',
    'const foldPairs =',
    `${lines.join('\n')};`,
    '',
  ].join('\n');
}

/** Route answers of the native router on a graph (also used to check the pack's graph). */
export function routeAnswers(graph: NativeGraph): Record<string, unknown>[] {
  const router = new NativeRouter(graph);
  return ROUTE_QUERIES.map((query) => {
    const stops = query.stops.map(([longitude, latitude]) => ({ latitude, longitude }));
    // As the provider does: routes with stops have no alternatives.
    const alternatives = stops.length > 2 ? 0 : query.alternatives;
    try {
      const result = router.route(query.profile, stops, alternatives, {
        language: query.language,
      });
      return { ...query, result };
    } catch (error) {
      if (!(error instanceof NoRouteError)) throw error;
      return { ...query, error: error.message };
    }
  });
}

async function answers(graph: NativeGraph, index: NativeSearchIndex) {
  const provider = new NativeGeocodingProvider(
    {
      get: () => Promise.resolve(index),
      available: () => Promise.resolve(true),
    } as unknown as NativeSearchStore,
    {
      get: () => Promise.resolve(graph),
      available: () => Promise.resolve(true),
    } as unknown as NativeGraphStore,
  );
  const searches = [];
  for (const query of SEARCH_QUERIES) {
    // As GeocodingService does before asking the provider.
    const text = query.text.trim().replace(/\s+/g, ' ');
    const results = await provider.search({
      text,
      limit: query.limit,
      near: query.near ? { longitude: query.near[0], latitude: query.near[1] } : undefined,
    });
    searches.push({ ...query, results });
  }
  const reverses = [];
  for (const point of REVERSE_QUERIES) {
    // GeocodingService rounds the tapped point to ~1 m.
    const longitude = Number(point[0].toFixed(5));
    const latitude = Number(point[1].toFixed(5));
    reverses.push({ point, result: await provider.reverse(latitude, longitude) });
  }
  return {
    format: 'route-maps-offline-expected',
    version: 1,
    packs: FIXTURE_PACKS,
    folds: FOLD_CASES.map((text) => [text, fold(text)]),
    routes: routeAnswers(graph),
    searches,
    reverses,
  };
}

/** One line per answer: small diffs when an engine changes. */
function serialize(expected: Record<string, unknown>): string {
  const lines: string[] = ['{'];
  const keys = Object.keys(expected);
  keys.forEach((key, position) => {
    const value = expected[key];
    const comma = position < keys.length - 1 ? ',' : '';
    if (Array.isArray(value)) {
      lines.push(`  ${JSON.stringify(key)}: [`);
      value.forEach((item, index) =>
        lines.push(`    ${JSON.stringify(item)}${index < value.length - 1 ? ',' : ''}`),
      );
      lines.push(`  ]${comma}`);
    } else {
      lines.push(`  ${JSON.stringify(key)}: ${JSON.stringify(value)}${comma}`);
    }
  });
  lines.push('}');
  return lines.join('\n') + '\n';
}
